package com.wrongweather.moipzy.domain.clothes.category;

public enum SmallCategory {
    // T_SHIRT, POLO_SHIRT : only NORMAL
    // OUTER : LIGHT, MEDIUM, HEAVY
    // HOODIE, SWEAT_SHIRT, KNIT : SWEATER
    CARDIGAN, DENIM_JACKET, BLOUSON, BLAZER, HOODED, //LIGHT OUTER
    MA1, STADIUM_JACKET, LEATHER_JACKET, JACKET,//MEDIUM OUTER
    COAT, PADDING,    //HEAVY OUTER
    T_SHIRT, POLO_SHIRT, LONG_SLEEVE, D_SHIRT, HOODIE, SWEAT_SHIRT, KNIT,  //상의 종류
    JEANS, SWEAT_PANTS, COTTON_PANTS, SLACKS, LINEN_PANTS, SHORTS
}
