name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    
    # 1. 코드 체크아웃
    - name: Checkout
      uses: actions/checkout@v4

    # 2. Java 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Gradle 설정
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v2
      with:
        gradle-version: '7.2'

    # 4. gradlew에 실행 권한 부여
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    # 5. src/main/resources 디렉토리 생성 (필요한 경우)
    - name: Create resources directory
      run: mkdir -p src/main/resources

    # 6. `application-ec2.yml`을 `resources` 폴더로 복사
    - name: Copy application-ec2.yml
      run: echo "${{ secrets.APPLICATION_EC2_YML }}" > src/main/resources/application.yml

    # 7. SpringBoot 애플리케이션 빌드
    - name: Build with Gradle Wrapper
      run: ./gradlew build
      
    # 8. Docker 이미지 빌드
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test .

    # 9. Docker Hub 로그인
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 10. Docker Hub에 푸시
    - name: Docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

  run-docker-image-on-ec2:
    needs: build-and-push-docker
    runs-on: self-hosted

    steps:

    # 1. Docker pull
    - name: docker pull
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

    # 2. Docker container stop
    - name: stop container
      run: |
        if [ $(sudo docker ps -a -q -f name=spring-cicd-test) ]; then
          docker stop spring-cicd-test
        fi

    # 3. Docker run new container
    - name: run new container
      run: docker run --rm -it -d -p 8080:8080 --name spring-cicd-test-container ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

    # 4. 도커 예전 이미지 삭제
    - name: delete old docker image
      run: docker system prune -f

